language: csharp
mono: latest
solution: Naggum.sln
install:
- nuget restore
- cd YogSothoth.Web && npm install && npm run webpack
script:
- xbuild /p:Configuration=Release /p:TargetFrameworkVersion="v4.5"
